"store the temporary files vim creates to a specific directory so they're not littering folders
set backupdir=~/vimtmp//,.
set directory=~/vimtmp//,.

" Display line and column number in bottom ruler.
set ruler
" Display the line numbers.
set number
" Activate syntax highlighting.
syntax enable
" Set a nice theme.
color slate


if has("gui_running")
  " Set a nicer font.
  set guifont=Consolas:h11:cDEFAULT
  " Hide the toolbar.
  set guioptions-=T
endif

" turn off obnoxious windows bells
set belloff=all
